### PR TITLE
Little game | 生成实体组-初始提交

### PR DESCRIPTION
**Pull request by Kawaa-qwq**
## Description
与其说是”小游戏“，我更喜欢称它为”生成实体组“。通过\resources\ExcelBinOutput\LittleGameData.json来生成

SCENE：

"id"——实体的顺序id
"gameId"——所在的实体组
"entityId"——实体id
"type"——实体类别（SCENE，MONSTER）
"pos"——生成位置
"rot"——生成旋转
"state"——我忘了，不管，总之后面大概有用

MONSTER：（后续会提交等级，默认伤害的pr，无需繁琐地写伤害）
"id"——实体的顺序id
"gameId"——所在的实体组
"entityId"——实体id
"type"——实体类别（SCENE，MONSTER）
"pos"——生成位置
”hpBase“——基础血量
”attackBase“——基础攻击力
”defenseBase“——基础防御力
”fireSubHurt”——火伤
->elec雷 grass草 water水 wind风 rock岩 ice冰 physical物理
"state"——我忘了，不管，总之后面大概有用

创建LittleGameData.json时需注意：
1，id从1开始，不能重复，重复会覆盖上一个id所属的数据
2，SCENE和MONSTER不一样，所需的数据也不一样，可多不可少
## Type of changes
- [ ] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Kawaa-qwq** [comment]
例子：
'[
    {
		"id": 1,
        "gameId": 1,
		"entityId": "41005004",
        "type": "SCENE",
		"pos": {
			"x": 2520,
			"y": 261,
			"z": -1492
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 2,
        "gameId": 1,
		"entityId": "41005004",
        "type": "SCENE",
		"pos": {
			"x": 2516.196,
			"y": 262.2707,
			"z": -1490.8466
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 3,
        "gameId": 1,
		"entityId": "41030002",
        "type": "SCENE",
		"pos": {
			"x": 2517.81,
			"y": 262.09293,
			"z": -1490.8087
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 4,
        "gameId": 2,
		"entityId": "42902018",
        "type": "SCENE",
		"pos": {
			"x": 2517.918,
			"y": 262.08,
			"z": -1488.421
		},
		"rot": {
			"x": 0,
			"y": 240.3712,
			"z": 0
		},
		"state": "scene"
    }
]'

**Comment by Kawaa-qwq** [comment]
例子：
`[
    {
		"id": 1,
        "gameId": 1,
		"entityId": "41005004",
        "type": "SCENE",
		"pos": {
			"x": 2520,
			"y": 261,
			"z": -1492
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 2,
        "gameId": 1,
		"entityId": "41005004",
        "type": "SCENE",
		"pos": {
			"x": 2516.196,
			"y": 262.2707,
			"z": -1490.8466
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 3,
        "gameId": 1,
		"entityId": "41030002",
        "type": "SCENE",
		"pos": {
			"x": 2517.81,
			"y": 262.09293,
			"z": -1490.8087
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 4,
        "gameId": 2,
		"entityId": "42902018",
        "type": "SCENE",
		"pos": {
			"x": 2517.918,
			"y": 262.08,
			"z": -1488.421
		},
		"rot": {
			"x": 0,
			"y": 240.3712,
			"z": 0
		},
		"state": "scene"
    }
]`

**Comment by Kawaa-qwq** [comment]
例子：
[
    {
		"id": 1,
        "gameId": 1,
		"entityId": "41005004",
        "type": "SCENE",
		"pos": {
			"x": 2520,
			"y": 261,
			"z": -1492
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 2,
        "gameId": 1,
		"entityId": "41005004",
        "type": "SCENE",
		"pos": {
			"x": 2516.196,
			"y": 262.2707,
			"z": -1490.8466
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 3,
        "gameId": 1,
		"entityId": "41030002",
        "type": "SCENE",
		"pos": {
			"x": 2517.81,
			"y": 262.09293,
			"z": -1490.8087
		},
		"rot": {
			"x": 0,
			"y": 0,
			"z": 0
		},
		"state": "scene"
    },
	{
		"id": 4,
        "gameId": 2,
		"entityId": "42902018",
        "type": "SCENE",
		"pos": {
			"x": 2517.918,
			"y": 262.08,
			"z": -1488.421
		},
		"rot": {
			"x": 0,
			"y": 240.3712,
			"z": 0
		},
		"state": "scene"
    }
]

**Comment by wcjqwq** [comment]
10086

**Comment by qianyu1431** [comment]
66666

**Comment by Kawaa-qwq** [comment]
> 66666

嘿嘿

**Comment by FeiFei-SS** [comment]
大佬o(*////▽////*)q

**Comment by Kawaa-qwq** [comment]
> 大佬o(_////▽////_)q

o(////▽////)q

**Pull request merged**
